# Generated by Django 5.2.9 on 2026-01-23 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HabitEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Выполнена"), ("missed", "Пропущена")], default="done", max_length=16
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("place", models.CharField(blank=True, max_length=255, null=True, verbose_name="Место")),
                ("time", models.TimeField(help_text="Базовое время напоминания", verbose_name="Время")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Приятная привычка")),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Ежедневно"), (7, "Еженедельно")], default=1, verbose_name="Периодичность (дни)"
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, null=True, verbose_name="Вознаграждение")),
                (
                    "execution_time",
                    models.PositiveSmallIntegerField(default=60, verbose_name="Время на выполнение (сек)"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичная")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_as_reward_for",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["id", "name"],
            },
        ),
    ]
