# Generated by Django 5.2.9 on 2026-01-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "period_type",
                    models.CharField(
                        choices=[("daily", "Ежедневно"), ("weekly", "Еженедельно")], default="daily", max_length=16
                    ),
                ),
                ("frequency", models.PositiveIntegerField(default=1)),
                ("time", models.TimeField(help_text="Базовое время напоминания")),
                ("is_pleasant", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HabitEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("done", "Выполнена"), ("missed", "Пропущена")], default="done", max_length=16
                    ),
                ),
            ],
        ),
    ]
